# Generated by Django 3.2 on 2021-05-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_personalblog_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalblog',
            name='tags',
        ),
    ]
